### ISSUE TITLE
 Create a common ESLint config

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/commons#1]
Currently different versions of it are being copy-pasted across projects. Ideally it should be strict. Ideally there should be a JS version.

**Comment by bbenligiray** [comment]
@Siegrift what do you think about keeping this sort of stuff in this repo as well?

**Comment by Siegrift** [comment]
The problem with this is that you want ESlint only as a dev dependency. If we create an eslint configuration here it will have other eslint plugins as dependencies. If you then install the commons, these dependencies will end up in prod deps.

One solution to this would be to have them as peer dependencies, but that is annoying to work with. I'd say that we can live with this for now and we can later convert it to monorepo (or separate package).
