### ISSUE TITLE
Implement blockchain utilities

### ISSUE THREAD

**Issue by Siegrift** [api3dao/commons#13]
There are many utilities which are used across API3 projects:
- deriveBeaconId
- deriveTemplateId
- deriveEndpointId
- deriveAirnodeXpub
- deriveSponsorWallet
- deriveSponsorWalletFromPath
- deriveBeaconSetId

We could also ship validation and types related to these:
- evmIdSchema (preferably without the EVM prefix)
- evmAddressSchema (preferably without the EVM prefix)

**Comment by Siegrift** [comment]
I now realized that Airseeker v2 will need `deriveWalletPathFromSponsorAddress` which is implemented in Airnode, which would also be nice to have implemented just a single time.

**Comment by aquarat** [comment]
In discussion decided on implementing ethers v5-based approach first (including good unit tests) and then eventually migrating to Viem in a separate issue.

**Comment by Siegrift** [comment]
fyi: this is the issue for that https://github.com/api3dao/commons/issues/29
