### ISSUE TITLE
Fix package.json path in release script 

### ISSUE THREAD

**Issue by dcroote** [api3dao/commons#134]
Currently the script reads the version from installed commons rather than the calling package's `package.json`.

> So most likely an issue with [this line](https://github.com/api3dao/commons/blob/037f90527012b124ae4ca5be3720a1a0efffcf99/src/release-scripts/tag-and-release.ts#L76).

**Comment by Siegrift** [comment]
I've mentioned that a solution could be:

> Maybe let the project pass it as an argument? And expose a function to parse the version given path to package.json?

but maybe there's a better way.

**Comment by andreogle** [comment]
The fix worked 🎉 Thanks
