### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by hiletmis** [api3dao/commons#17]
Cannot import commons functions.

Webpack gives the following error:

`Module build failed: UnhandledSchemeError: Reading from "node:assert" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
...
...`

@Siegrift 

Tried to solve it by myself but I couldn't.

**Comment by Siegrift** [comment]
Did you try to import processing features in frontend application?

**Comment by hiletmis** [comment]
Yeah we will utilize processing functions to develop a pusher config ui;
https://github.com/api3dao/tasks/issues/209

**Comment by andreogle** [comment]
I'm not sure that using the current processing feature from this library in a frontend app is the correct approach? Most of the available [features/modules](https://github.com/api3dao/commons/blob/3ca961cb1b40f693e0a0087fd4bcfc9ec394128f/src/processing/unsafe-evaluate.ts#L41-L78) are intended to be run in a Node.js sandbox/server environment. The only way I can see processing working is by posting content to the server and running it there.

Or am I misunderstanding and you can't even bundle/build the application?

**Comment by hiletmis** [comment]
I will try to move it to a backend service. There are workarounds on webpack side. But moving the processing to a backend service can be better.

Thanks.
