### ISSUE TITLE
Implement timestamp post-processing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/commons#27]
Currently, Airnode uses the API call time as the `timestamp` of the signed data. This doesn't cover two use cases:

- We want Airnode to make an API call to an RPC endpoint to get chain data. We want `timestamp` to be the most recent block timestamp. (This is what Nodary does for [LSD feeds](https://github.com/api3dao/tasks/issues/200) at the moment.)
- The API that the Airnode call returns includes as timestamp field. We want `timestamp` to be that.

As a solution, I'm proposing a `timestampPostProcessingSpecifications` field at the same level as `postProcessingSpecifications`. This works exactly like `postProcessingSpecifications`, except `output` of that will be used as `timestamp` (rather than `data`).

This obviously requires a change in the OIS format. The field can be optional similar to `postProcessingSpecifications`, which makes this a non-breaking change.

EDIT: This requires changes in multiple projects.
- [x] OIS - https://github.com/api3dao/ois/pull/117
- [x] Docs (because of OIS change) - https://github.com/api3dao/vitepress-docs/pull/669
- [x] Commons - https://github.com/api3dao/commons/pull/32
- [x] Airnode - https://github.com/api3dao/airnode/pull/1914
- [x] Pusher - https://github.com/api3dao/signed-api/pull/133

**Comment by bbenligiray** [comment]
@dcroote for visibility

**Comment by bbenligiray** [comment]
The alternative way of doing this is piggybacking on `postProcessingSpecifications`. In addition to defining an `output`, `postProcessingSpecifications` can define a `timestamp`. This is somewhat breaking in terms of a potential naming collision.

**Comment by Siegrift** [comment]
An alternative would be to create `postProcessingSpecificationsV2` and change the format of the snippets. Couple of possibilities, some already mentioned on the call:
* Make it return values instead of assigning to output field. The output schema of the function would be `{value, timestamp}`
* Revisit how input data is passed. Currently `input` and `endpointParameters` and we risk a naming collision whenever we want to add new value. Making it `inputData` object helps with this because we can just add new keys to the object. This is still not bulletproof though.
* We could make the specification not be an array (not sure if anyone used this featrue).
* We could omit the `environment` and support just `Node async`. If the processing is a function that returns some value, we can wrap it in `new Promise` to force it to be async and await it.

**Comment by bbenligiray** [comment]
> We could make the specification not be an array (not sure if anyone used this featrue).

I don't see how this is an improvement

> We could omit the environment and support just Node async

It would be nice to have a [Node (restricted)](https://nodejs.org/api/permissions.html) environment in the future once that stuff is more fleshed out so I'm not a fan of removing that field. I'm fine with forcing `async` though.

**Comment by Siegrift** [comment]
> I don't see how this is an improvement

To me the array version feels like an unnecessary complexity. Both user has to think about why the specification is an array and we need to handle chaining the values through multiple processing snippets.

**Comment by bbenligiray** [comment]
We ended up never using it (says something for modular design imo) but considering that it's already there and working, I don't see the reason to remove it

**Comment by Siegrift** [comment]
I think you misunderstood this:

> An alternative would be to create postProcessingSpecificationsV2 and change the format of the snippets. 

I mean to create a new field which implements couple of improvements + delivers this new feature. We would still support the "legacy" post-processing though. We would ensure that only one of `postProcessingSpecifications` and `postProcessingSpecificationsV2` is specified using OIS validation.

**Comment by bbenligiray** [comment]
For reference I had agreed with `postProcessingSpecificationsV2` and was nit-picking above

**Comment by Siegrift** [comment]
As a note, this requires docs changes as well.

**Comment by Siegrift** [comment]
I've updated a bunch of PRs (links in the editted issue description).

**Comment by metobom** [comment]
Will ChainAPI use this change too?

**Comment by bbenligiray** [comment]
See https://api3workspace.slack.com/archives/C0436H2BJKE/p1700466668070539
