### ISSUE TITLE
Discuss setting up a "common" system for error notifications

### ISSUE THREAD

**Issue by BTT21000** [api3dao/commons#56]
As discussed at the OEV auctioneer call on 01/03/24 and as per this https://github.com/api3dao/oev-auctioneer/issues/132#issuecomment-1959777661, the below components would require notifications for errors:
- oev-auctioneer (https://github.com/api3dao/oev-auctioneer/issues/132)
- Airnode feeds and Signed APIs (https://github.com/api3dao/oev-auctioneer/issues/132#issuecomment-1959777661)

The notifications system could then be plugged to monitoring (e.g. OpsGenie) so that the monitoring team can supervise in case of emergency.

**Comment by Siegrift** [comment]
There is a similar issue in tasks https://github.com/api3dao/tasks/issues/817.

I am not sure commons is the right place for this because there will be no work done in commons for this issue.

**Comment by BTT21000** [comment]
Noted, I have added the label Monitoring & Alterting to https://github.com/api3dao/tasks/issues/817 and added a comment to it https://github.com/api3dao/tasks/issues/817#issuecomment-1974678127

@PrenaamD for visibility

**Comment by BTT21000** [comment]
Tracked by https://github.com/api3dao/tasks/issues/817
